home/mini-course/controllers/AuthController.php
<?php
/**
 * Project:     mini-course
 * File:        AuthController.php
 * Author:      planet17
 * DateTime:    M10.D31.2016 6:50 PM
 */

namespace app\controllers;

use app\models\students\InForm;

use yii;
use yii\web\Controller;

use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class AuthController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['in', 'logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => ['in'],
                        'allow' => true,
                        'roles' => ['?', '@']
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Login action.
     * 
     * Method return true when login is successful.
     * 
     * At other cases return string of rendered template of the login form.
     * 
     * @return true|string
     */
    public function renderPartialLoginPanel()        
    {
        $model = new InForm();
        
        if ($model->load(Yii::$app->request->post())) {
            if ($model->login()) {               
                return true;
            }

            Yii::$app->session->setFlash('loginError');
        }

        return $this->renderPartial('//auth/form-in', [
            'model' => $model
        ]);
    }
    
    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

home/mini-course/controllers/CourseController.php
<?php
/**
 * Project:     mini-course
 * File:        CourseController.php
 * Author:      planet17
 * DateTime:    M10.D31.2016 1:23 AM
 */

namespace app\controllers;

use app\models\courses\models\CoursesProcess;
use app\models\courses\forms\CustomStartForm;

use app\models\courses\models\Result;
use yii;
use yii\base\Exception;
use yii\filters\AccessControl;

/**
 * Class CourseController.
 *
 * @package app\controllers.
 *
 * @property CoursesProcess|null
 */
class CourseController extends AuthController
{
    /** @var string $defaultAction Override default action */
    public $defaultAction = 'start';

    /**
     * Override beforeAction method.
     *
     * @param yii\base\Action $action
     * @return boolean
     * @throws Exception
     * @throws yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        Yii::$app->course->fixBy($action);

        if (!parent::beforeAction($action)) {
            return false;
        }

        return Yii::$app->course->secureValidation();
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'start',
                    'step',
                    'complete',
                    'continue-course',
                    'expired'
                ],
                'rules' => [
                    [
                        'actions' =>
                            [
                                'step',
                                'complete',
                                'continue-course',
                                'expired'
                            ],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                    [
                        'actions' => ['start'],
                        'allow' => true,
                        'roles' => ['?', '@']
                    ]
                ]
            ]
        ];
    }

    /**
     * Display Homepage and it page for start New Course and page for login.
     * 
     * @return string
     *
     * @throws \Exception
     */
    public function actionStart()
    {
        $model = new CustomStartForm();

        if ($model->load(Yii::$app->request->post())) {
            $model->check();
        }

        /** @var string $renderedPartTop|boolean */
        if (Yii::$app->user->isGuest) {
            /** @var string|true $renderedPartTop */
            $renderedPartTop = parent::renderPartialLoginPanel();

            if ($renderedPartTop === true) {
                if (Yii::$app->course->secureValidation()) {
                    $model->runConstructor();
                }
            }

        } else {
            $renderedPartTop = $this->renderPartialStartPanel($model);
        }
        
        return $this->render('pages/start', [
            'renderedPartTop' => $renderedPartTop,
            'model' => (new Result())->getLastResults()
        ]);
    }

    /**
     * @param integer $step Number from 2 to 7
     * @return string
     */
    public function actionStep($step)
    {
        Yii::$app->course->checkPost();
        
        if (!Yii::$app->course->prepareStep()) {
            return $this->redirect(yii\helpers\Url::to(['course/complete']));
        }
        
        return $this->render(
            Yii::$app->course->getTemplatePath(),
            Yii::$app->course->getContent()
        );
    }

    /**
     * 
     */
    public function actionComplete()
    {
        /** @var Result $studentLastResults */
        $studentLastResults = (new Result())->getLastResultForCurrentStudent();
        
        return $this->render('pages/complete', [
            'name' => Yii::$app->user->identity->login,
            'results' => $studentLastResults
        ]);
    }

    /**
     * @return string
     */
    public function actionExpired()
    {
        return $this->render('pages/expired');
    }

    /**
     * @return string
     */
    public function actionContinueCourse()
    {
        return $this->render('pages/continue-course', [
            'currentStep' => Yii::$app->course->info->current_step
        ]);
    }

    /**
     * @param $model
     * @return string
     */
    protected function renderPartialStartPanel(&$model)
    {
        return $this->renderPartial('forms/general/form-start', [
            'userLgn' => Yii::$app->user->identity->login,
            'model'   => $model
        ]);
    }
}

home/mini-course/controllers/SiteController.php
<?php

namespace app\controllers;

use yii;
use yii\web\Controller;
/**
 * Class SiteController.
 *
 * Default Yii-controller. I keep it for errorHandler.
 *
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ]
        ];
    }
}

home/mini-course/views/course/forms/general/form-start.php
<?php
/**
 * Project:     mini-course
 * File:        form-start.php
 * Author:      planet17
 * DateTime:    M11.D02.2016 4:12 PM
 *
 * Partial template of header with your name and button for next step.
 *
 * @var $this yii\web\View
 * @var $userLgn string
 * @var $model \app\models\courses\forms\CustomStartForm
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

/** @var string $formTemplate Html-string template for each input at the form */
$formTemplate = "<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>"; ?>

<!-- start::form-start::your-login -->
<div class="your-login">
    <p>Your login: <strong><?= $userLgn; ?></strong></p>
</div>
<!-- end::form-start::your-login -->

<!-- start::form-start::form -->
<?php
/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'id' => 'start-form',
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template' => $formTemplate,
        'labelOptions' => ['class' => 'col-lg-1 control-label']
    ]]);

echo $form->field($model, 'hiddenJack')->hiddenInput(['value' => true]); ?>
<div class="form-group">
    <div class="col-lg-offset-0 col-lg-12">
        <?= Html::submitButton(
            'Next!',
            ['class' => 'btn btn-primary', 'name' => 'start-button']
        ); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!-- end::form-start::form -->

home/mini-course/views/course/forms/general/test.php
<?php
/**
 * Project:     mini-course
 * File:        test.php
 * Author:      planet17
 * DateTime:    M11.D03.2016 8:53 PM
 * 
 * @var $this yii\web\View
 * @var $model app\models\courses\forms\TypeTestGeneralForm
 * @var $nextStep integer
 *
 */
use yii\bootstrap\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;

$this->title = 'Test!';

/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'action' => Url::to(['step', 'step' => $nextStep]),
    'id' => 'start-form',
    'options' => ['class' => 'form-horizontal']
]);
echo $form->field($model, 'test')->hiddenInput(); ?>
    <div class="form-group">
        <div class="col-lg-offset-0 col-lg-12">
            <?= Html::submitButton(
                'Test!',
                ['class' => 'btn btn-primary', 'name' => 'start-button']
            ); ?>
        </div>
    </div>
<?php ActiveForm::end(); ?>

home/mini-course/views/course/forms/types/checkbox.php
<?php
/**
 * Project:     mini-course
 * File:        checkbox.php
 * Author:      planet17
 * DateTime:    M11.D04.2016 3:01 AM
 *
 * @var $this yii\web\View
 * @var $model \app\models\courses\forms\QuestionTodayRadioForm
 * @var $nextStep integer
 * @var $question string
 * @var $helper string
 */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\helpers\Url;

/** @var string $formTemplate Html-string template for each input at the form */
$formTemplate = "<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>"; ?>

<!-- start::checkbox -->
<h3><?= $question; ?></h3>

<?php

/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'action' => Url::to(['step', 'step' => $nextStep]),
    'id' => 'checkbox-form',
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template' => $formTemplate,
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ]]);

echo $form->field($model, 'selected', [
    'inline' => false,
    'enableLabel' => false
])->checkboxList(
    Yii::$app->course->info->getContent()->temporaryQuestionSettings->content->options,
    ['class' => 'btn-group', 'data-toggle' => 'buttons', 'unselect' => null]
);
?>
<div class="form-group">
    <div class="col-lg-offset-0 col-lg-12">
        <?= Html::submitButton(
            'Next!',
            ['class' => 'btn btn-primary', 'name' => 'start-button']
        ); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!-- end::checkbox -->

home/mini-course/views/course/forms/types/input.php
<?php
/**
 * Project:     mini-course
 * File:        input.php
 * Author:      planet17
 * DateTime:    M11.D06.2016 12:54 AM
 *
 * @var $this yii\web\View
 * @var $model \app\models\courses\forms\InputForm
 * @var $nextStep integer
 * @var $question string
 */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\helpers\Url;

/** @var string $formTemplate Html-string template for each input at the form */
$formTemplate = "<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>"; ?>

<!-- start::read -->
<h3><?= $question; ?></h3>

<?php

/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'action' => Url::to(['step', 'step' => $nextStep]),
    'id' => 'input-form',
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template' => $formTemplate,
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ]]);

echo $form->field($model, 'field')->input(
    'number',
    [
        'placeholder' => $model->attributeLabels()['field'],
        'autofocus' => true
    ]
); ?>
<div class="form-group">
    <div class="col-lg-offset-0 col-lg-12">
        <?= Html::submitButton(
            'Next!',
            ['class' => 'btn btn-primary', 'name' => 'start-button']
        ); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!-- end::read -->

home/mini-course/views/course/forms/types/radio.php
<?php
/**
 * Project:     mini-course
 * File:        radio.php
 * Author:      planet17
 * DateTime:    M11.D04.2016 3:01 AM
 *
 * @var $this yii\web\View
 * @var $model \app\models\courses\forms\QuestionTodayRadioForm
 * @var $nextStep integer
 * @var $question string
 * @var $helper string
 */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;
use yii\helpers\Url;

$model->field = 0;

/** @var string $formTemplate Html-string template for each input at the form */
$formTemplate = "<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>"; ?>

<!-- start::radio -->
<h3><?= $question; ?></h3>

<?php

/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'action' => Url::to(['step', 'step' => $nextStep]),
    'id' => 'radio-form',
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template' => $formTemplate,
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ]]);

echo $form->field($model, 'field', [
    'inline' => false,
    'enableLabel' => false
])->radioList(
    Yii::$app->course->info->getContent()->temporaryQuestionSettings->content->options,
    ['class' => 'btn-group', 'data-toggle' => 'buttons', 'unselect' => null]
);
?>
<hr><div class="help-block"><?= $helper; ?></div><hr>
<div class="form-group">
    <div class="col-lg-offset-0 col-lg-12">
        <?= Html::submitButton(
            'Next!',
            ['class' => 'btn btn-primary', 'name' => 'start-button']
        ); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!-- end::radio -->

home/mini-course/views/course/forms/types/read.php
<?php
/**
 * Project:     mini-course
 * File:        read.php
 * Author:      planet17
 * DateTime:    M11.D04.2016 3:01 AM
 *
 * @var $this yii\web\View
 * @var $model \app\models\courses\forms\ReadForm
 * @var $nextStep integer
 * @var $question string
 */
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

/** @var string $formTemplate Html-string template for each input at the form */
$formTemplate = "<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>"; ?>
<!-- start::read -->
<h3><?= $question; ?></h3>

<?php
/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'action' => \yii\helpers\Url::to(['step', 'step' => $nextStep]),
    'id' => 'read-form',
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template' => $formTemplate,
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ]]);
echo $form->field($model, 'hiddenJack')->hiddenInput(['value' => true]); ?>
<div class="form-group">
    <div class="col-lg-offset-0 col-lg-12">
        <?= Html::submitButton(
            'Next!',
            ['class' => 'btn btn-primary', 'name' => 'start-button']
        ); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!-- end::read -->

home/mini-course/views/course/forms/types/video.php
<?php
/**
 * Project:     mini-course
 * File:        video.php
 * Author:      planet17
 * DateTime:    M11.D04.2016 2:28 PM
 *
 * @var $this yii\web\View
 * @var $model \app\models\courses\forms\ReadForm
 * @var $videoLink string
 * @var $nextStep integer
 * @var $question string
 */

use yii\bootstrap\ActiveForm;
use yii\bootstrap\Html;

/** @var string $formTemplate Html-string template for each input at the form */
$formTemplate = "<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-5\">{error}</div>"; ?>
<!-- start::video -->
<h3><?= $question; ?></h3>

<!-- start::video::video -->
<div class="videoWrapper col-lg-offset-0 col-lg-12">
    <div id="player"></div>
    <script>
        /**
         * @description Object type of Youtube API.
         * @type {*}
         * @name Player
         */
        var Player;

        /**
         * @description Duration of video at seconds.
         * @type {Number}
         * @name vDuration
         */
        var vDuration = 0;

        /**
         * @description Boolean flag. When watching start it set by true.
         * @type {boolean}
         * @name onWatchingFlag
         */
        var onWatchingFlag = false;

        /**
         * @description Boolean flag.
         * When timer complete blocking attempt for changes it set by true.
         * @type {boolean}
         * @name onTimeSpent
         */
        var onTimeSpent = false;

        var firstScriptTag,
            tag = document.createElement('script');

        tag.src = "https://www.youtube.com/iframe_api";

        firstScriptTag = document.getElementsByTagName('script')[0];
        firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

        /**
         * @function onYouTubeIframeAPIReady
         * @description Function calls by Youtube API.
         */
        function onYouTubeIframeAPIReady() {
            Player = new YT.Player('player', {
                height: '270', width: '480',
                videoId: '<?= $videoLink; ?>',
                events: {
                    'onReady': onPlayerReady,
                    'onStateChange': onPlayerStateChange
                }
            });
        }

        /**
         * @function onPlayerReady
         * @description Function call by eventHandler (onReady) at Player.
         * @param e {event}
         */
        function onPlayerReady(e) {
            vDuration = parseInt(Player.getDuration() * 0.95);
        }

        /**
         * @function onPlayerStateChange
         * @description Function call by eventHandler (onStateChange) at Player.
         * @param e {event}
         */
        function onPlayerStateChange(e) {
            /* Set delay when Player start playing. */
            if (e.data == 1) {
                if (!onWatchingFlag) {
                    onWatchingFlag = true;
                    setTimeout(changeLookResult, (vDuration * 1000));
                }
            }

            /* Set value of watching result to TRUE! */
            if (e.data == 0) {
                if (onTimeSpent) {
                    $('input[name="VideoForm[hiddenJack]"]').val(1);
                }
            }
        }

        /**
         * @function changeLookResult
         * @description Function call by eventHandler (onStateChange) at Player.
         * It call at event when state is watching after and not immediately, over delay.
         */
        function changeLookResult() {
            onTimeSpent = true;
        }
    </script>
</div>

<!-- end:video:video -->

<?php
/** @var ActiveForm $form */
$form = ActiveForm::begin([
    'action' => \yii\helpers\Url::to(['step', 'step' => $nextStep]),
    'id' => 'video-form',
    'options' => ['class' => 'form-horizontal'],
    'fieldConfig' => [
        'template' => $formTemplate,
        'labelOptions' => ['class' => 'col-lg-1 control-label'],
    ]]);
echo $form->field($model, 'hiddenJack')->hiddenInput(['value' => 0]); ?>

<div class="form-group">
    <div class="col-lg-offset-0 col-lg-12">
        <?= Html::submitButton(
            'Next!',
            ['class' => 'btn btn-primary', 'name' => 'start-button']
        ); ?>
    </div>
</div>
<?php ActiveForm::end(); ?>
<!-- end::video -->

home/mini-course/views/course/pages/complete.php
<?php
/**
 * Project:     mini-course
 * File:        complete.php
 * Author:      planet17
 * DateTime:    M11.D05.2016 5:20 PM
 *
 * Template for case when your watch last result of Course.
 *
 * @var $this yii\web\View
 *
 * @var $name string
 * @var $results \app\models\courses\models\Result|null
 */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Congratulations!';
?>

<!-- start::complete -->
<div class="site-complete">
    <h1><?= Html::encode($this->title); ?></h1>
    <hr>
    <div class="result-table">
        <?php if ($results === null) { ?>
            <p><span>hacker detected!</span></p>
        <?php } else { ?>
            <p><span><?= $name; ?></span>, you had finished course!</p>
            <hr>
            <p>Your last score: <span><?= $results->points; ?> points</span>.</p>
            <hr>
            <p>The total time of your course: <span><?= $results->time_spent; ?> seconds</span>.</p>
            <hr>
            <div class="form-group">
                <div class="col-lg-offset-0 col-lg-12">
                    <?= Html::a('Back to Start', Url::to(['course/start']), [
                        'class' => 'btn btn-primary',
                    ]); ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>
<!-- end::complete -->

home/mini-course/views/course/pages/continue-course.php
<?php
/**
 * Project:     mini-course
 * File:        continue-course.php
 * Author:      planet17
 * DateTime:    M11.D01.2016 9:47 PM
 *
 * Template for case when your Course expired.
 *
 * @var $this yii\web\View
 *
 * @var $currentStep integer
 *
 */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Continue your course!';
?>

<!-- start::continue-course -->
<div class="site-continue">
    <h1><?= Html::encode($this->title); ?></h1>
    <div class="alert alert-info">
        You have course now! Just continue it!
    </div>
    <div class="form-group">
        <div class="col-lg-offset-0 col-lg-12">
            <?= Html::a('Continue', Url::to(['step', 'step' => $currentStep]), [
                'class' => 'btn btn-primary',
            ]); ?>
        </div>
    </div>
</div>
<!-- start::continue-course -->

home/mini-course/views/course/pages/expired.php
<?php
/**
 * Project:     mini-course
 * File:        expired.php
 * Author:      planet17
 * DateTime:    M11.D01.2016 9:48 PM
 * 
 * Template for case when your Course expired.
 *
 * @var $this yii\web\View
 *
 */
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = 'Your course expired! Take new!';
?>

<!-- start::expired -->
<div class="site-expired">
    <h1><?= Html::encode($this->title); ?></h1>
    <div class="alert alert-info">
        Your course had expired now! You can start new!
    </div>
    <div class="form-group">
        <div class="col-lg-offset-0 col-lg-12">
            <?= Html::a('Continue', Url::home(), [
                'class' => 'btn btn-danger',
            ]); ?>
        </div>
    </div>
</div>
<!-- end::expired -->

home/mini-course/views/course/pages/start.php
<?php
/**
 * Project:     mini-course
 * File:        start.php
 * Author:      planet17
 * DateTime:    M10.D31.2016 6:08 PM
 *
 * Template for Homepage.
 *
 * @var $this yii\web\View
 * @var $renderedPartTop string
 * @var $model \app\models\courses\models\Result[]
 *
 */
use yii\bootstrap\Html;

$this->title = 'Start course!';
?>

<!-- start::start -->
<div class="site-index">
    <div class="content-top">
        <h1><?= Html::encode($this->title); ?></h1>
        <hr>
        <?= $renderedPartTop; ?>
    </div>
    <hr>
    <div class="content-results">
        <h3>Last results:</h3>
        <hr>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover table-condensed last-results">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Score</th>
                    <th>Time spent</th>
                </tr>
                </thead>
                <tbody>
                <?php if (count($model)) { ?>
                    <?php foreach ($model as $result) { ?>
                        <tr>
                            <td><?= $result->getStudent()->login; ?></td>
                            <td><?= $result->points; ?></td>
                            <td><?= $result->time_spent; ?></td>
                        </tr>
                    <?php } ?>
                <?php } else { ?>
                    <tr>
                        <td colspan="3" style="text-align: center;">No results found.</td>
                    </tr>
                <?php } ?>
                </tbody>
            </table>
        </div>

    </div>
</div>
<!-- end::start -->

home/mini-course/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
$this->beginPage();
?><!DOCTYPE html>
<html lang="<?= Yii::$app->language; ?>">
<head>
    <meta charset="<?= Yii::$app->charset; ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title); ?></title>
    <?php $this->head(); ?>
</head>
<body>
<?php $this->beginBody(); ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'Course',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    if (Yii::$app->course->info !== null) {
        $step = Yii::$app->course->info->current_step;
    } else {
        $step = false;
    }


    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            [
                'label' => "{$step}/7",
                'url' => null,
                'class' => 'sexy-label',
                'visible' => ($step > 1 && $step <= 6)
            ],
            Yii::$app->user->isGuest ? (
                ['label' => 'Login', 'url' => Yii::$app->homeUrl]
            ) : (
                '<li>'
                . Html::beginForm(['/auth/logout'], 'post')
                . Html::submitButton(
                    'Logout (' . Yii::$app->user->identity->login . ')',
                    ['class' => 'btn btn-link logout']
                )
                . Html::endForm()
                . '</li>'
            )
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]); ?>
        <?= $content; ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; Course <?= date('Y'); ?></p>

        <p class="pull-right"><?= Yii::powered(); ?></p>
    </div>
</footer>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>

home/mini-course/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */
use yii\helpers\Html;
$this->title = $name;
?><div class="site-error">
    <h1><?= Html::encode($this->title); ?></h1>
    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)); ?>
    </div>
    <p>The above error occurred while the Web server was processing your request.</p>
    <p>Please contact us if you think this is a server error. But I think you are just a bad hacker!</p>
</div>